# Exemplo de CD para publicar o projeto no Google Cloud Run através do Google Cloud Build

# Lista de passos a serem executados
steps:

# Build da imagem Docker do projeto
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/devfest2023-rv/devfest-rv/demo:$COMMIT_SHA', '.']


# Push da imagem do container para o Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/devfest2023-rv/devfest-rv/demo:$COMMIT_SHA']

# Execucao do comando de publicacao no Google Cloud Run
# neste passo que pode ser definido onde o código será publicado
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'hello-rv'
  - '--image'
  - 'gcr.io/devfest2023-rv/devfest-rv/demo:$COMMIT_SHA'
  - '--region'
  - 'us-central1'